json.id sla_policy.id
json.name sla_policy.name
json.description sla_policy.description
json.first_response_time_threshold sla_policy.first_response_time_threshold
json.resolution_time_threshold sla_policy.resolution_time_threshold
json.only_during_business_hours sla_policy.only_during_business_hours
json.created_at sla_policy.created_at.to_i
json.updated_at sla_policy.updated_at.to_i
